// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpikyhhtgvnjhdzdqfst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwaWt5aGh0Z3ZuamhkemRxZnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0Njg1MDYsImV4cCI6MjA3NTA0NDUwNn0.0NDZ76wek227HUhqiPEdj71jWpnDftJMDrMf3j-2mn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});